Error out on unknown options.

diff --git a/devel/rebuild b/devel/rebuild
--- a/devel/rebuild
+++ b/devel/rebuild
@@ -23,7 +23,6 @@ update=false
 openai_url="https://raw.githubusercontent.com/openai/openai-openapi/master/openapi.yaml"
 target_dir="share/openapi.yaml"
 
-POSITIONAL=()
 while [[ $# -gt 0 ]]
 do
 key="$1"
@@ -46,12 +45,12 @@ case $key in
     exit;
     ;;
     *)    # unknown option
-    POSITIONAL+=("$1") # save it in an array for later
-    shift # past argument
+    echo "Error: Unknown option: $1"
+    show_help
+    exit 1
     ;;
 esac
 done
-set -- "${POSITIONAL[@]}" # restore positional parameters
 
 set -Eeuo pipefail
 
